#---ETAPA 1: Build (construccion) ---
FROM maven:3.9.16-eclipse-temurin-21-alpine AS builder
WORKDIR /app
COPY . .
#RUN tiempo de ejecucion
RUN mvn clean package -DskipTests

#---ETAPA 2: RUNTIME (El producto final) ---
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=builder /app/target/*.jar product.jar
EXPOSE 8080
#ENTRYPOINT es que debe hacer el contenedor cuando alguien da play
ENTRYPOINT [ "java", "-jar", "product.jar" ]